### PR TITLE
Add Tesla's Source

### PR DESCRIPTION
**Pull request by fishtreesugar**

### CODE REVIEW

**Comment by erkmos** [comment]
Sorry for the delay. Thanks, but the link seems to be incorrect. I see no mention of Tesla in there?

**Comment by utdemir** [comment]
I think OP meant this link: https://www.reddit.com/r/haskell/comments/8smtw0/fall_2018_internship_opportunity_with_tesla_inc/

**Comment by fishtreesugar** [comment]
oops, fixed :D

**Comment by erkmos** [comment]
Great, thanks!

**Pull request merged**
