### PR TITLE
Remove Fairvioo

### PR DESCRIPTION
**Pull request by celinelouvet**
Fairvioo is no longer alive :(

### CODE REVIEW

**Comment by erkmos** [comment]
Website seems gone yeah, and not much other information to go on, I will remove them. Thanks for the update!

**Comment by erkmos** [comment]
I assume you worked there or had some other connection to the company?

**Comment by celinelouvet** [comment]
Yes, I was the CTO.

**Comment by llelf** [comment]
@celinelouvet What happened?

**Comment by celinelouvet** [comment]
It was a new startup. We didn't succeed in raising funds, apparently due to a bad estimation of the market. We had to close everything recently :)

**Pull request merged**
