### PR TITLE
Add Bellroy

### PR DESCRIPTION
**Pull request by noughtmare**
Also from this reddit thread: https://reddit.com/r/haskell/comments/s1tu2j/job_2x_haskell_developer_bellroy_remote/, but I think the GitHub will be more useful in the future.

### CODE REVIEW

**Comment by erkmos** [comment]
Thanks!

**Comment by fake-rookie** [comment]
i think it is not.

Just few 'Hello World' level and tutorial of their repo.

**Comment by noughtmare** [comment]
You're kind of right, filtering on Haskell misses their https://github.com/bellroy/wai-handler-hal project which is just slightly more Nix than Haskell, but it does list https://github.com/bellroy/aws-arn. And both these projects are very small.

I wouldn't mind if anyone changes it back to the reddit job ad.

**Comment by JackKelly-Bellroy** [comment]
We use Haskell a lot internally and plan on doing more, just haven't had that much time lately to open-source new things.

**Pull request merged**
