### PR TITLE
Add Sumall

### PR DESCRIPTION
**Pull request by kanishka-azimi**
@taphu might have more details

### CODE REVIEW

**Comment by taphu** [comment]
Sector is "Artificial Intelligence".  Remote is OK.

**Comment by taphu** [comment]
Thanks!

**Comment by taphu** [comment]
Also, https://sumall.ai is more representative of the future direction of the company. Thanks again!

**Comment by kanishka-azimi** [comment]
I deleted my fork, so maybe you can make this edit in a bit after this is merged?

**Comment by taphu** [comment]
Absolutely.

**Comment by erkmos** [comment]
Thanks

**Pull request merged**
