### PR TITLE
Jotron

### PR DESCRIPTION
**Pull request by unhammer**

### CODE REVIEW

**Comment by erkmos** [comment]
Hi, thanks for the update. The ad looks a lot like it is trying to lure haskell engineers to a standard C++/C# job..

@yobson can you shed some light on to what extent you use haskell at Jotron, if you still work there? 10%? 50%? 90%?

**Comment by yobson** [comment]
Hahaha. It almost is!

One project uses haskell, but we want to expand that if we get more haskell devs. I spend about 25% of my time in haskell land. When I'm working on that project, maybe 60%.

**Comment by yobson** [comment]
Apologies for the third comment. I've only just realised what's going on. I wouldn't add the link to the job posting (it really pains me to say). That would be miss leading. At the moment, 90% of your job would be C# or C++. I don't want to disappoint anyone. If someone wants that job, but also wants to help with the haskellification as a very minor part of the job, feel free to apply (please)! But it wouldn't be a haskell job primarily!

**Comment by erkmos** [comment]
Didn't mean to close this, sorry, wrong button. 

Thanks for the clarification (and honesty). If I remember correctly; my original intent with this list was to create a list of companies that use haskell as a major technology in their stack/products/services (not exclusively) since it is a pretty rare to find a company that uses it. 

Maybe I should add a column that indicates whether it is a major or minor technology to let anyone interested make their own decision. This kind of job could e.g. be useful for someone that already knows C++ but wants to get some real-world experience with haskell... Unfortunately that information would be missing for almost all companies on this list.

I understand if you have an up-hill struggle increasing haskell use at your company as it can be pretty hard to find engineers that know it (engineers that know C# comparatively grow on trees).

**Comment by yobson** [comment]
I think that extra column would be a really good idea!

**Comment by erkmos** [comment]
Seems I forgot about this PR, sorry about that! I have thought about it and will merge it with one minor change

**Pull request merged**
